language: generic 
sudo: required
services: 
  - docker

before_install:
  - docker build -t kleinkauff/docker-react -f Dockerfile.dev

script:
  - docker run -e CI=true kleinkauff/docker-react npm run test -- --coverage