language: generic 
sudo: required
services: 
  - docker

before_install:
  - docker build -t kleinkauff/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kleinkauff/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: us-west-2
  app: docker-react
  env: Dockerreact-env
  bucket_name: elasticbeanstalk-us-west-2-596254623058
  bucket_path: docker-react
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY